platform :ios, '9.3'

target 'Demo' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Demo
  pod 'ObservableKit'
  pod 'SWMailgun', :git => 'https://github.com/limadeveloper/SWMailgun.git', :branch => 'fix/access_modifiers'
end