platform :ios, '9.3'

target 'Demo' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Demo
  pod 'BaseNetworkKit', :git => 'https://github.com/limadeveloper/BaseNetworkKit.git', :branch => 'master'
  pod 'ObservableKit'
end
